# Module 2 — Data Cleaning, Analysis, Feature Engineering

### Module 2 Part 1

# 1. Import Pandas and Read the CSV File

In [2]:
import pandas as pd
df = pd.read_csv("../01_Data/Titanic.csv")

In [3]:
# Find all mising values in every column of Dataset.
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### What I Learned
`isnull()` identifies missing values and `sum()` counts them column-wise.

In [4]:
# 2. Fill all missing value of Age with there Median.
df["Age"] = df["Age"].fillna(df["Age"].median())

# check null values in Age column 
df["Age"].isnull().sum()

np.int64(0)

### What I Learned
`isnull()` identifies missing values and `sum()` counts them column-wise.

In [5]:
# 3.Find all unique values of Sex.
display(df["Sex"].unique())

array(['male', 'female'], dtype=object)

### What I Learned
`unique()` returns the distinct values present in a column.

In [6]:
# 4. Count all values of male & female in Sex.
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

### What I Learned
`value_counts()` counts how many times each unique value appears in a column.

In [7]:
# Q5. Find mean, median, minimum, and maximum of Fare.
display(df["Fare"].mean())
display(df["Fare"].median())
display(df["Fare"].min())
display(df["Fare"].max())

np.float64(32.204207968574636)

np.float64(14.4542)

np.float64(0.0)

np.float64(512.3292)

### What I Learned
`mean()`, `median()`, `min()`, and `max()` give different summary measures for the Fare column.

In [8]:
# Q6. Find all datatypes of Dataframe.
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### What I Learned
`df.dtypes` shows the data type of every column in the DataFrame.

In [10]:
# Q7. Extract the unique values of Pclass and their frequencies/value counts.
df['Pclass'].value_counts().sort_index()

# OBSERVATION: Frequency means the count of identical values, meaning how many times a specific value has repeated.

Pclass
1    216
2    184
3    491
Name: count, dtype: int64

### What I Learned
`value_counts()` gives the frequency of each Pclass value, and `sort_index()` orders those class labels.

#  Module 2  Part 2 Practice

In [11]:
# Q8.Find the average Fare groupby Sex.
df.groupby("Sex", observed=False)["Fare"].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

### What I Learned
`groupby()` separates the data by Sex and `mean()` calculates the average Fare for each group.

In [12]:
# Q9. Find the average Age groupby Pclass.
df.groupby("Pclass", observed=False)["Age"].mean()

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64

### What I Learned
`groupby()` can calculate the average Age separately for each passenger class.

In [13]:
# Q10. Find the average Fare grouped by Sex and Pclass.
df.groupby(["Sex", "Pclass"], observed=False)["Fare"].mean()

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

### What I Learned
`groupby()` can use two columns to calculate a separate average Fare for each combination.

In [14]:
# Q11. Create a new column: FamilySize
df["FamilySize"] = df['SibSp'] + df['Parch'] + 1
df['FamilySize']

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: FamilySize, Length: 891, dtype: int64

### What I Learned
How to create a new feature from existing columns by combining SibSp, Parch, and the passenger themself.

In [15]:
df["AgeGroup"] = df["Age"]({
    df['Age'],
    bins = [0, 18, 60, 10],
    labels = ["Child", "Young", "Adult", "Old"],
)}

SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' on line 1 (11605616.py, line 5)

### What I Learned
How this Pandas operation solves the question and how to interpret the result.

# Realization

Right now, I am unable to solve all the Day 4 problems properly. Looking at what I did above, I feel like I didn't do them correctly—the questions were asking one thing, but my answers were completely different. Now, I am going to rewrite all the concepts and code for Day 4 from scratch before attempting the questions again, just like the way I practiced on Day 3 before solving those problems!

# Module Part 2 Practice ke liye practice of some eassy questions.

# Single column groupby - 8 Questions

In [16]:
# Count passengers groupby Sex
print(df.groupby("Sex", observed=False)["PassengerId"].count())  #first method
print(df["Sex"].value_counts()) #second method

Sex
female    314
male      577
Name: PassengerId, dtype: int64
Sex
male      577
female    314
Name: count, dtype: int64

### What I Learned
`value_counts()` counts how many times each unique value appears in a column.

In [17]:
# Find the average Age groupby Sex.
df.groupby("Sex", observed=False)["Age"].mean()

Sex
female    27.929936
male      30.140676
Name: Age, dtype: float64

### What I Learned
`groupby()` separates the Sex column into two groups `male` and `female` and `mean()` calculates an average for each group.

In [18]:
# Find the average Fare groupby Pclass.
df.groupby("Pclass", observed=False)["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

### What I Learned
`groupby()` separates the Pcass column into groups and `mean()` calculates an average for each group.

In [19]:
# Find the passengers count groupby Passenger class.
df.groupby("Pclass", observed=False)["PassengerId"].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

### What I Learned
`groupby()` seperates  the Pclass column into groups and count() calculate each passenger of every group.

In [20]:
# Find the average Age groupby Sex.
df.groupby("Sex", observed=False)["Age"].mean()

Sex
female    27.929936
male      30.140676
Name: Age, dtype: float64

### What I Learned

I learned that `groupby()` separates Sex column into two groups `male` and `female` and `mean()` calculates an average for each group.

In [21]:
# Find the average Age groupby Pclass
df.groupby("Pclass", observed=False)["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

### What I Learned
`groupby()` separates Pclass column into groups and `mean()` calculates an average for each group.

In [22]:
# Count all passengers groupby Embarked.
df.groupby("Embarked", observed=False)["PassengerId"].count()

Embarked
C    168
Q     77
S    644
Name: PassengerId, dtype: int64

### What I Learned
`groupby()` is used to perform calculations on Embarked column for separate into different groups and count() calculate counting of each group.

In [23]:
# Find total survived passengers groupby Sex.
df.groupby("Sex", observed=False)["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

### What I Learned

`sum()` can total the Survived values within each Sex group, giving the number of survivors when Survived is coded as 0 and 1.


### Key learnings after running and inderstand this question
count() = total passengers in each sex group

sum() = total survivors in each sex group

# 2. Multiple groupby() — 5 Question

In [25]:
# Find the number of passengers groupby Sex and Pclas.
df.groupby(["Pclass", "Sex"], observed=False)["PassengerId"].count()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: PassengerId, dtype: int64

### What I Learned

I learned that multiple-column grouping creates combinations of groups, but summing PassengerId is not the correct way to count passengers because First time when I solve this problem by self then I use sum() for count passengers; `count()` is used for counts.

In [26]:
# Calculate the average Age grouped by Pclass and Sex combined.
df.groupby(["Pclass", "Sex"], observed=False)["Age"].mean()

Pclass  Sex
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64

### What I Learned
It reveals average age per gender and class subgroup, enabling accurate missing-data imputation and demographic insight extraction.

In [ ]:
# Calculate the average Fare grouped by Embarked and Pclass.
df.groupby(["Embarked", "Pclass"], observed=False)["Fare"].mean()

Embarked  Pclass
C         1         104.718529
          2          25.358335
          3          11.214083
Q         1          90.000000
          2          12.350000
          3          11.183393
S         1          70.364862
          2          20.327439
          3          14.644083
Name: Fare, dtype: float64

### What I Learn
Multi-column grouping to calculate average metrics per combined category.

In [ ]:
# Calculate the count grouped by Sex and Survived.
df.groupby(["Sex", "Survived"], observed=False)["PassengerId"].count()

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: PassengerId, dtype: int64

### What I Learned
How to group data by multiple categorical variables and count records per group using Pandas.

In [27]:
# Calculate the average fare based on Pclass and Survived.
df.groupby(["Pclass", "Survived"], observed=False)["Fare"].mean()

Pclass  Survived
1       0           64.684007
        1           95.608029
2       0           19.412328
        1           22.055700
3       0           13.669364
        1           13.694887
Name: Fare, dtype: float64

### What I Learned
Group data by multiple categories to calculate the average value of a target column.

# Aggregation — 5 Question

In [27]:
# Calculate the minimum, maximum, and average of the Age column.
df["Age"].agg(["min", "max", "mean"])

min      0.420000
max     80.000000
mean    29.361582
Name: Age, dtype: float64

### What I Learn
This code calculates three summary statistics—minimum, maximum, and average—for Age, helping understand the dataset’s age range and typical passenger age.

In [28]:
# Calculate the total of the Fare column.
df["Fare"].agg("sum")

np.float64(28693.9493)

### What I Learn
This code uses agg() with sum to add every Fare value, returning the total fare collected across all passengers together.

In [29]:
# Calculate the total number of passengers in the dataset.
df["PassengerId"].agg("sum")

np.int64(397386)

### What I Learn
This code adds all PassengerId values; it does not count passengers, so use `df["PassengerId"].count()` to find the actual total passenger.

In [30]:
# Calculate the minimum and maximum values of the SibSp column.
df["SibSp"].agg(["min", "max"])

min    0
max    8
Name: SibSp, dtype: int64

### What I Learn
This code uses `agg()` to calculate the smallest and largest SibSp values, showing the range of siblings or spouses aboard.

In [34]:
# Find the number of unique values in the Pclass column.
df["Pclass"].agg("nunique")
# .agg('unique') output: array([3, 1, 2])
# .agg('nunique') output: 3

3

### What I Learn
This code returns distinct values from `Pclass`; it does not count them. Use `unique()` to get their total count correctly. To count unique values, use nunique() instead.

# Multiple Aggregation — 5 Questions

In [188]:
# syntax of multiple aggrigation
df.groupby("Sex", observed=False).agg({
    "Age": "mean",
    "Fare": "mean"
})

              Age       Fare
Sex
female  27.929936  44.479818
male    30.140676  25.523893

### What I Learn
This code groups passengers by sex and calculates average age and fare independently for each gender category within the dataset.

In [ ]:
# How can you calculate the total Fare and minimum PassengerId for each unique Age value?
df.groupby("Age", observed=False).agg({
    "Fare": "sum", 
    "PassengerId": "min"
})

           Fare  PassengerId
Age
0.42     8.5167          804
0.67    14.5000          756
0.75    38.5166          470
0.83    47.7500           79
0.92   151.5500          306
...         ...          ...
70.00   81.5000          673
70.50    7.7500          117
71.00   84.1584           97
74.00    7.7750          852
80.00   30.0000          631

[88 rows x 2 columns]

### What I Learn
This code groups passengers by Age, calculates total Fare, and returns the smallest PassengerId within each Age group for comparison.

In [35]:
# How do you use groupby() with multiple aggregation functions?
"""I use groupby() with multiple aggrigation like this:"""
df.groupby("Sex", observed=False).agg({
    "Age": "mean",
    "Pclass": "sum",
    "Fare": "size"
})

              Age  Pclass  Fare
Sex
female  27.929936     678   314
male    30.140676    1379   577

### What I Learn
This groups passengers by sex, calculates average age, sums passenger classes, and counts fare records separately for each sex group.

In [36]:
# How can you find the total fare and average age for each passenger class?
df.groupby("Pclass", observed=False).agg({
    "Fare" : "sum",
    "Age" : "mean"
})

              Fare        Age
Pclass
1       18177.4125  36.812130
2        3801.8417  29.765380
3        6714.6951  25.932627

### What I Learned
This groups passengers by class, calculates total fares, and computes average ages, providing two summary statistics for each passenger class.

In [38]:
# How do you rename aggregation results after using .agg()?
df.groupby("Survived", observed=False).agg({
    "Fare" : "mean",
    "Age" : "mean"
    }).rename(columns={"Fare" : "Average _Ticket_price", "Age" : "Average_Age"})

          Average _Ticket_price  Average_Age
Survived
0                     22.117887    30.028233
1                     48.395408    28.291433

### What I Learned
This code groups passengers by survival status, calculates average fare and age, then renames the resulting columns for clearer interpretation.

# Creating New Columns - 5 questions

In [39]:
# How do you create a new column called FamilySize by adding SibSp and Parch?
FamilySize = df["SibSp"] + df["Parch"] + 1
df["FamilySize"]

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: FamilySize, Length: 891, dtype: int64

### What I Learned
This code calculates each passenger’s FamilySize by adding siblings, spouses, parents, children, and the passenger themselves, storing results in FamilySize.

In [40]:
# How can you create a column that shows whether a passenger is an adult or child?
df["AgeGroup"] = pd.cut(
    df['Age'],
    bins = [0, 18, 60],
    labels = ["child", "adult"]
)
df['AgeGroup']

0      adult
1      adult
2      adult
3      adult
4      adult
       ...
886    adult
887    adult
888    adult
889    adult
890    adult
Name: AgeGroup, Length: 891, dtype: category
Categories (2, object): ['child' < 'adult']

### What I Learned
In this code categorizes passengers by age, labeling ages 0–18 as children and 18–60 as adults in a new AgeGroup column.

In [41]:
# How do you create a new column using values from an existing column?
df["Child"] = (df["Age"] < 18).map({True: "Yes", False: "No"})
print(df['Child'].value_counts())

Child
No     778
Yes    113
Name: count, dtype: int64

### What I Learned
 Child column by checking whether Age is below 18, then maps True to Yes and False to No.

In [42]:
# How can you calculate the fare per family member?
Fare_per_member = df['Fare'] / df['FamilySize']
print(Fare_per_member)

0       3.62500
1      35.64165
2       7.92500
3      26.55000
4       8.05000
         ...
886    13.00000
887    30.00000
888     5.86250
889    30.00000
890     7.75000
Length: 891, dtype: float64

### What I Learned
This divides each passenger’s fare by their family size, calculating the average fare paid per family member.

In [43]:
# How do you create a column using an if-else condition?
df["adult"] = df["Age"].apply(
    lambda Age: "Yes" if Age>=18 else "No"
)
print(df["adult"].value_counts())

adult
Yes    778
No     113
Name: count, dtype: int64

### What I Learned
Creates an adult column by checking each passenger’s age: 18 or older is labeled “Yes,” otherwise “No”; value_counts() summarizes categories.

# rename() — 5 Question

In [44]:
# How do you rename the column Sex to Gender?
df.rename(columns={"Sex":"Gender"}, inplace=True)
df['Gender'].head()

0      male
1    female
2    female
3    female
4      male
Name: Gender, dtype: object

### What I Learned
This code renames the Sex column to Gender permanently, then displays the first five values to verify the change succeeded.

In [45]:
# How can you rename multiple columns at the same time?
df.rename(columns={"PassengerId":"PassId", 
                   "SibSp": "Siblings_Spouse",
                   "Parch": "Parents_Childs"}, inplace=True)
df[['PassId','Siblings_Spouse', 'Parents_Childs']].head()

   PassId  Siblings_Spouse  Parents_Childs
0       1                1               0
1       2                1               0
2       3                0               0
3       4                1               0
4       5                0               0

### What I Learned
code renames three columns simultaneously and displays their first five rows for quick verification using the updated column names.

In [46]:
# How can you change first 3 index number to alphabet?
df.rename(index={0:'A', 1:'B', 2:'C'}, inplace=True)
df.head()

,PassId,Survived,Pclass,Name,Gender,Age,Siblings_Spouse,Parents_Childs,Ticket,Fare,Cabin,Embarked,FamilySize,AgeGroup,Child,adult
A,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,adult,No,Yes
B,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,adult,No,Yes
C,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,adult,No,Yes
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,adult,No,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,adult,No,Yes

### What I Learned
This code renames the first three DataFrame index labels from 0, 1, and 2 to A, B, and C, respectively.

In [47]:
# What is the difference between using inplace=True and assigning the result to the DataFrame?
"""When we use inplace=True, the DataFrame is modified directly in memory.
Without inplace=True, Pandas returns a new DataFrame with the changes, and we must assign it back to a variable or to the same DataFrame.

For example:
df.rename(columns={"Sex": "Gender"}, inplace=True)  # original DataFrame changes
df = df.rename(columns={"Sex": "Gender"})  # new DataFrame is created and assigned
"""

'When we use inplace=True, the DataFrame is modified directly in memory.\nWithout inplace=True, Pandas returns a new DataFrame with the changes, and we must assign it back to a variable or to the same DataFrame.\n\nFor example:\ndf.rename(columns={"Sex": "Gender"}, inplace=True)  # original DataFrame changes\ndf = df.rename(columns={"Sex": "Gender"})  # new DataFrame is created and assigned\n'

### What I Learned
inplace=True modifies the existing DataFrame; assignment creates a modified DataFrame and stores it back in the variable.

In [48]:
# How do you check whether a column was renamed successfully?
"""Calling the renamed column in the dataframe(df)"""
"Gender" in df.columns

True

### What I Learned
code checks whether the DataFrame contains the renamed “Gender” column, confirming that the renaming operation succeeded correctly as expected.

# Cleaning Data — 10 Question

## Duplicate Rows

In [49]:
# How do you check whether a DataFrame contains duplicate rows?
display(df.duplicated().sum()) #first methode 
display(df.duplicated().any())  # second method

np.int64(0)

np.False_

### What I Learned
The `duplicated()` method returns Boolean values; `sum()` counts duplicate rows, while `any()` checks whether at least one duplicate row exists.

In [50]:
# Which Pandas function is used to count duplicate rows?
df.duplicated().sum()

np.int64(0)

### What I Learned
The `duplicated()` method identifies duplicate rows, while `sum()` returns the number of duplicates in the DataFrame as an integer.

In [51]:
# How do you remove duplicate rows?
df = df.drop_duplicates()

### What I Learned
This code removes duplicate rows from the DataFrame, returns the cleaned result, and assigns it back to the variable `df`.

In [52]:
# How can you keep only the first occurrence of a duplicate row?
df = df.drop_duplicates(keep="first")

### What I Learned
This code removes duplicate rows, preserves only their first occurrence, and stores the cleaned DataFrame back in the `df` variable.

In [53]:
# How do you check the number of rows before and after removing duplicates?
before = len(df)

new_df = df.drop_duplicates()

after = len(new_df)

print(f"Before: " , before)
print("After: " ,after)

Before:  891
After:  891

### What I Learned
This code records the original row count, removes duplicate rows, records the cleaned count, and compares both totals clearly afterward.

In [54]:
# How do you display all column names in a DataFrame?
display(df.columns)

Index(['PassId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age',
       'Siblings_Spouse', 'Parents_Childs', 'Ticket', 'Fare', 'Cabin',
       'Embarked', 'FamilySize', 'AgeGroup', 'Child', 'adult'],
      dtype='object')

### What I Learned
`display(df.columns)` shows every column name in the DataFrame, helping you inspect its structure and verify available fields.

In [55]:
# How do you check whether two Column names are duplicated?
df.columns.duplicated().sum()

np.int64(0)

### What I Learned
This code counts duplicate column names by returning Boolean values and summing `True` values, revealing the total number of duplicates.

In [56]:
# How can you remove extra spaces from the beginning and end of column names?
df.columns.str.strip()

Index(['PassId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age',
       'Siblings_Spouse', 'Parents_Childs', 'Ticket', 'Fare', 'Cabin',
       'Embarked', 'FamilySize', 'AgeGroup', 'Child', 'adult'],
      dtype='object')

### What I Learned
`df.columns.str.strip()` removes leading and trailing spaces from every column name, ensuring clean, consistent labels for reliable DataFrame operations.

In [57]:
# How do you convert all column names to lowercase?
df.columns.str.lower()

Index(['passid', 'survived', 'pclass', 'name', 'gender', 'age',
       'siblings_spouse', 'parents_childs', 'ticket', 'fare', 'cabin',
       'embarked', 'familysize', 'agegroup', 'child', 'adult'],
      dtype='object')

### What I Learned
This converts every DataFrame column name to lowercase, making labels consistent and easier to reference in Pandas data analysis operations.

In [58]:
# How can you replace spaces in column names with underscores?
df.columns.str.strip().str.replace(" ", "_")

Index(['PassId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age',
       'Siblings_Spouse', 'Parents_Childs', 'Ticket', 'Fare', 'Cabin',
       'Embarked', 'FamilySize', 'AgeGroup', 'Child', 'adult'],
      dtype='object')

### What I Learned
This strips extra spaces from column names and replaces internal spaces with underscores, creating consistent labels for reliable DataFrame operations.

# Saving a CSV File — 5 Question

In [228]:
# How do you save a DataFrame as a CSV file?
df.to_csv("new_Titanic.csv", index=False)

### What I Learned
This code saves the DataFrame as a CSV file named `new_Titanic.csv` without including the DataFrame's index as an extra column.

In [59]:
# How can you save the file inside the 04_Output folder?
"""Like that: """
df.to_csv("../04_Output/new.csv", index=False)

### What I Learned
This code saves the DataFrame as `new.csv` inside the `04_Output` folder, excluding row index numbers from the final CSV file.

In [230]:
# What is the purpose of index=False in to_csv()?
"""The Purpose  of 'index=False' in 'to_csv' to keep the CSV clean and avoid adding an extra unwanted index column."""

"The Purpose  of 'index=False' in 'to_csv' to keep the CSV clean and avoid adding an extra unwanted index column."

### What I Learned
`index=False` prevents Pandas from saving the DataFrame index as an extra CSV column, keeping exported files clean and organized.

In [60]:
# How can you save a cleaned DataFrame as cleaned_titanic.csv?
df.to_csv("../04_Output/cleaned_titanic.csv", index=False)

### What I Learned
This code saves the cleaned DataFrame as `cleaned_titanic.csv` inside the `04_Output` folder without writing row index values to the file.

In [61]:
# How do you verify that the CSV file was saved successfully?
"""Open 04_Output folder and check manualy """

saved_df = pd.read_csv("../04_Output/cleaned_titanic.csv")
saved_df.head()

,PassId,Survived,Pclass,Name,Gender,Age,Siblings_Spouse,Parents_Childs,Ticket,Fare,Cabin,Embarked,FamilySize,AgeGroup,Child,adult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,adult,No,Yes
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,adult,No,Yes
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,adult,No,Yes
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,adult,No,Yes
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,adult,No,Yes

### What I Learned
This code reloads the saved CSV, confirms it can be opened successfully, and displays its first five rows for verification.

# <<<Now I have separated all the Module 2 Part 2 problems that I was struggling to solve into five or more different sections.>>>

# Day 4 practice Again with Practice and confidence

In [75]:
import pandas as pd
df = pd.read_csv("../01_Data/Titanic.csv")

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Q8:Find the average Fare groupby Sex
df.groupby("Sex", observed=True)["Fare"].mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [78]:
# Q9: Find the average Age groupby Pclass
df.groupby("Pclass", observed=True)["Age"].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [80]:
# Q10: Find the average Fare grouped by  Pclass and Sex
df.groupby(["Pclass", "Sex"], observed=True)["Fare"].mean()

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [81]:
# Q11:Create new column called FamilySize, formula: SibSp + Parch + 1
df['FamilySize'] = df["SibSp"] + df["Parch"] + 1
df['FamilySize']

0      2
1      2
2      1
3      2
4      1
      ..
886    1
887    1
888    4
889    1
890    1
Name: FamilySize, Length: 891, dtype: int64

In [82]:
# Q12: Rename the `Sex` column to `Gender`.
df.rename(columns={"Sex": "Gender"}, inplace=True)
df["Gender"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Gender, Length: 891, dtype: object

In [83]:
# Q13: Check duplicate rows in whole dataset.
df.duplicated().sum()

np.int64(0)

In [84]:
# Q14: Remove Duplicate rows.
df = df.drop_duplicates()

In [85]:
# Q15:Create an AgeGroup column.
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins = [0, 18, 60, 100],
    labels = ["Child", "Adult", "Senior"]
)
df['AgeGroup'].value_counts()

AgeGroup
Adult     553
Child     139
Senior     22
Name: count, dtype: int64

# Now I done doing practice day 4

# Now I Do 🎯 Homework like An Internship Task
### *Task : Clean and analyze the Titanic dataset and prepare it for further analysis.*

In [92]:
# Import required library & read csv
import pandas as pd
df = pd.read_csv("../01_Data/Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Part A — Data Cleaning
### *Main objective: To clean and prepare the dataset for analysis.*

In [93]:
# Create a complete report of missing values.
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [94]:
# Fill the missing values in the `Age` column with its median.
df["Age"] = df["Age"].fillna(df["Age"].median())

In [95]:
# Handle missing values Embarked appropriately.
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [96]:
# Check and remove duplicate rows.
df.duplicated().sum()

np.int64(0)

### Observation
There is no duplicates in this dataset so I dont remove any row in current dataset.

In [97]:
# Check datatypes of all column.
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

### Observation

*The PassengerId, Survived, Pclass, SibSp, and Parch columns have the `int64` data type. The Age and Fare columns have the `float64` data type. The Name, Sex, Ticket, Cabin, and Embarked columns have the `object` data type. Columns with integer or floating-point data types are called `numerical columns`, while columns with the `object` data type are called `categorical columns`.*
````

### WHAT I DO IN PART - A
*I checked the dataset for missing values and filled the missing values in the Age column with its median. I handled the missing values in the Embarked column by filling them with its mode. I also checked for duplicate rows and found that there were no duplicates. Finally, I reviewed the data types of all columns.*

# Part B — Analysis
### *Main objective: To understand patterns and groups within the Titanic dataset*

In [98]:
# Count the number of male's and female's in  Sex column.
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [99]:
# Find frequency of Pclass.
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [100]:
# Find Gender-wise average Age.
df.groupby("Sex", observed=False)["Age"].mean()

Sex
female    27.929936
male      30.140676
Name: Age, dtype: float64

In [ ]:
# Find the average fare groupby Pclass.
df.groupby("Pclass", observed=False)["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [101]:
#  Find the count of passengers grouped by Pclass and Sex.
df.groupby(["Pclass", "Sex"], observed=False)["PassengerId"].count()

Pclass  Sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: PassengerId, dtype: int64

### WHAT I DO IN PART - B
*I counted the male and female passengers and calculated the frequency of each passenger class. I also calculated the average age by gender and the average fare by passenger class. Additionally, I calculated the number of passengers based on both gender and passenger class.*

# Part C — Feature Engineering
### *Main objective: To create useful features for further analysis and machine learning.*

In [102]:
# Create FamilySize column.
df["FamilySize"] = df["Parch"] + df["SibSp"] + 1
display(df['FamilySize'].head(5))

0    2
1    2
2    1
3    2
4    1
Name: FamilySize, dtype: int64

In [103]:
# Create AgeGroup column.
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins = [0, 18, 60, 100],
    labels= ["Child", "Adult", "Seniore"]
)
display(df["AgeGroup"].head(5))

0    Adult
1    Adult
2    Adult
3    Adult
4    Adult
Name: AgeGroup, dtype: category
Categories (3, object): ['Child' < 'Adult' < 'Seniore']

In [109]:
# Create categories basis on FamilySize:
# 1 → Alone
# 2–4 → Small Family
# 5+ → Large Family

df["Category_FamilySize"] = pd.cut(
    df['FamilySize'],
    bins = [0, 1, 4, float("inf")],
    labels = ["Alone", "Small Family", "Large Family"]
)

display(df['Category_FamilySize'].head())

0    Small Family
1    Small Family
2           Alone
3    Small Family
4           Alone
Name: Category_FamilySize, dtype: category
Categories (3, object): ['Alone' < 'Small Family' < 'Large Family']

### observation: 
*When I first attempted this question and viewed the `head(20)` output, I realized that I had made a mistake. Families with 2–4 members were incorrectly being classified as **Alone** instead of **Small Family**.*

*After correcting the bins, the **Small Family** label worked properly. However, the **Large Family** label was still showing `NaN`. I asked ChatGPT for help by sharing an image, and I learned that to correctly classify families with 5 or more members, I needed to use:*

`bins = [0, 1, 4, float("inf")]`

*After trying this, I understood the concept clearly. If NumPy is also being used, I can write `np.inf` instead of `float("inf")`.*


### WHAT I DO IN - Part C

*I created a `FamilySize` column using the formula: `FamilySize = SibSp + Parch + 1`. I also created an `AgeGroup` column with the categories `Child`, `Adult`, and `Senior`. Furthermore, I categorized passengers into `Alone`, `Small Family`, and `Large Family` groups based on their family size.*

# Part D — Final Cleaning & Save 
### *Main objective: To create and save a final analysis-ready dataset.*

In [110]:
# Rename the Sex column to Gender.
df.rename(columns={"Sex": "Gender"}, inplace=True)

display(df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Gender', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize',
       'AgeGroup', 'Category_FamilySize'],
      dtype='object')

In [111]:
# Keep only these columns in the final dataset: `Name`, `Gender`, `Age`, `Pclass`, `Fare`, `FamilySize`, and `AgeGroup`.
df = df.drop(columns=["PassengerId", "Survived", "SibSp", "Parch", "Ticket", "Cabin", "Embarked", "Category_FamilySize"])
display(df.columns)

Index(['Pclass', 'Name', 'Gender', 'Age', 'Fare', 'FamilySize', 'AgeGroup'], dtype='object')

In [112]:
# Save the final cleaned dataset as `titanic_cleaned.csv`.
df.to_csv("../04_Output/titanic_cleaned.csv", index=False)

### WHAT I DO IN - PART D

*I renamed the `Sex` column to `Gender` and removed the unnecessary columns. I kept only the required columns: `Name`, `Gender`, `Age`, `Pclass`, `Fare`, `FamilySize`, and `AgeGroup`.Finally, I saved the cleaned dataset as `titanic_cleaned.csv` in the `04_Output` folder.*